version: "3.9"
services:
  frontend:
    container_name: icog-underconstruction
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Only mount node_modules, avoid overwriting .next
    command: ["sh", "-c", "pnpm build && pnpm start"]

